### ISSUE TITLE
SVG rect broken

### ISSUE THREAD

**Issue by rondonjon** [sairion/svg-inline-loader#1]
The following RegExp breaks `<rect>` tags because it removes their `width` and `height` attributes!

```
                 .replace(/width="\d+(\.\d+)?(px)?"/gi, "")
                 .replace(/height="\d+(\.\d+)?(px)?"/gi, "")
```

**Comment by rondonjon** [comment]
Do you think you could restrict the RegExp's to SVG tags only?

**Comment by sairion** [comment]
Thanks for report. I've never thought about it (usually I use this to remove useless crust from SVGs generated by Sketch and Photoshop, which is usually `<g />`, not serious one) but it should be done. ;) I will look into that.
