### ISSUE TITLE
Link to svg-inline-react in the readme

### ISSUE THREAD

**Issue by peterobrien** [sairion/svg-inline-loader#19]
Hey, like the work, 

sorry can't easily supply a PR right now, but in the readme you should link to `svg-inline-react` i.e. `[svg-inline-react](https://github.com/sairion/svg-inline-react)`, otherwise it's not clear what package you mean

**Comment by sairion** [comment]
Good catch. It's now in https://github.com/sairion/svg-inline-loader/commit/7596d9a2e0fb7a0066f0a1bef0835fe0f5d244f3

Thanks for suggestion! :)
