### ISSUE TITLE
how to use with angular template?

### ISSUE THREAD

**Issue by surfjedi** [sairion/svg-inline-loader#21]
This may ne silly question but how would I set this up with an angular template?

As in for angular materail design:
  <md-button class="md-icon-button" aria-label="Favorite">
          <md-icon md-svg-icon="img/icons/favorite.svg" style="color: greenyellow;"></md-icon>
        </md-button>

I have configed the loader, but how do I get the the url?

**Comment by sairion** [comment]
I do not have good knowledge of Angular template though, I think angular template loader (like https://github.com/WearyMonkey/ngtemplate-loader) should support nested `require()` call to support my loader or manually replace its svg element like what html-loader (https://github.com/webpack/html-loader) do. I think dealing with templates is not much of svg loader's responsibility.
