### ISSUE TITLE
removingTags not respected in loader config

### ISSUE THREAD

**Issue by phopkins** [sairion/svg-inline-loader#23]
It seems that specifying 'removingTags' in the loader config in my webpack.config.js file is having no effect. Looking at the code, it appears that the `isRemovingTag` function only looks at `defaultConfig` and not any passed-in config.

Is that intentional or a bug?

**Comment by sairion** [comment]
Thanks for report, it seems like definitely a bug! I will patch it soon. Thanks for report.

**Comment by sairion** [comment]
Fixed by https://github.com/sairion/svg-inline-loader/commit/94483a4be187c483df6fa9f45f0afe8b9b35ca51

**Comment by phopkins** [comment]
Cheers!
