### ISSUE TITLE
This package duplicates functionality of svgo-loader

### ISSUE THREAD

**Issue by tarikjn** [sairion/svg-inline-loader#25]
After doing some research around svg support in the webpack ecosystem, I have found [svgo-loader](https://github.com/rpominov/svgo-loader) to pretty much handle almost all of the functionally of this module and then much more. Furthermore, it it based around [svgo](https://github.com/svg/svgo) which is more standarized.

My recommendation would be to deprecate this package and recommend users use `svgo-loader` instead.

**Comment by sairion** [comment]
No, I don't need to do that. :)
