### ISSUE TITLE
self-closing tags broken during output generation

### ISSUE THREAD

**Issue by rondonjon** [sairion/svg-inline-loader#3]
Version 0.2.0 uses `simple-html-tokenizer` to parse and re-generate the svg contents.

This module seems to generate HTML4 output und not XML-compatible output.

Two independent elements `<svg><rect ... /><circle ... /></svg>` are then treated as if they contained each other in browser like Chrome and Firefox:

`<svg><rect><circle></svg>` is treated as if the `<rect>` was a parent (!) of the `<circle>`, and that is not valid according to SVG syntax, so the elements are completely removed from the display area.

**Comment by rondonjon** [comment]
I have found two interesting links on this topic:
 * http://tiffanybbrown.com/2011/03/23/html5-does-not-allow-self-closing-tags/
 * http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5

It seems that tags like `<rect ... />` are valid (and recommended) in standalone SVG files (because they're XML) but *not* in HTML5 (which seems to permit only a very limited number of self-closing tags, so-called "void" tags).

The list of HTML5 "void" elements contains no SVG elements: http://www.w3.org/html/wg/drafts/html/master/syntax.html#void-elements

This could mean that all self-closing SVG tags should be split up into start and end tags.

**Comment by rondonjon** [comment]
I have created a pull request for this issue.
Maybe you can check it out and merge.

**Comment by sairion** [comment]
Thanks. I chose `simple-html-tokenizer` for its minimalist approach, but maybe I was a bit naive :( PR seems nice, I will merge and do some refactor (and maybe some test). Thanks for your contribution! :+1:

**Comment by sairion** [comment]
Fixed by #4
