### ISSUE TITLE
Migration instructions from svg-inline-loader to svg-inline-react

### ISSUE THREAD

**Issue by 2metres** [sairion/svg-inline-loader#33]
Would it be possible to explain why this library is deprecated as well as outline how one might migrate to using your other library as you suggest

**Comment by morlay** [comment]
Just a solution in my projects.
https://github.com/morlay/react-app-starter/blob/master/webpack.babel.js#L113-L117

**Comment by sairion** [comment]
This library is not deprecated, just 'IconSVG' component is removed since this is webpack loader library, not a component library.
